export default {
  tour: null,
  tours: null,
  TServices: null,
  TourSchedule: null,
  TourGuide: null,
  TourType:null,
  ServicesTour: null,
  TristType_price: null,
  infoContact: {
    TourID: "",
    ContactName: "",
    ContactEmail: "",
    ContactPhone: "",
    ContactAddress: "",
    ContactNote: "",
  },
  Tourist: {
    touristType: "",
    touristName: "",
    touristSex: "",
    touristDate: "",
    touristPrice: "",
    servicesPrice: "",
  },
};
