export default {
  tour: null,
  tours: null,
  TServices: null,
  TourSchedule: null,
  TourGuide: null,
  TourType: null,
  ServicesTour: null,
  TristType_price: null,
  infoContact: {
    contactID: "",
    TourID: "",
    ContactName: "",
    ContactEmail: "",
    ContactPhone: "",
    ContactAddress: "",
    ContactNote: "",
  },
  Tourist: {
    touristID: "",
    touristType: "",
    touristName: "",
    touristSex: "",
    touristDate: "",
    touristPrice: "",
    servicesPrice: "",
  },
  Tourist_TouristServices: {
    servicesID: "",
    touristID: "",
    tServicesID: "",
  },
  Booking: {
    tourID: "",
    infoContactID: "",
    userID: "",
    extraPrice: "",
    currentPrice: "",
    totalPrice: "",
    payment: "",
    status: "",
    tourCheckinDays: "",
    tourCheckoutDays: "",
    departure: "",
    destination: "",
    bookingName: "",
    bookingDay: "",
  },
};
